EXTRA_CFLAGS := -I$(src)/common/inc -DNUM_METERS=$(METER_NUM) -DMETER_INIT_STR="$(METER_INITS)" -DMETER_EXTERN_STR="$(METER_EXTERNS)"

MODNAME = meter

obj-m := $(MODNAME).o

include $(src)/Kbuild_inc
