EXTRA_CFLAGS := -I$(src)/common/inc -DNUM_METERS=$(METER_NUM) -DMETER_INIT_STR="$(METER_INITS)" -DMETER_EXTERN_STR="$(METER_EXTERNS)"

MODNAME = meters

obj-m := $(MODNAME).o
$(MODNAME)-y := 

include $(src)/Kbuild_inc
